### ISSUE TITLE
createExplicitHashKey could create keys that fail validation with validateExplicitHashKey

### ISSUE THREAD

**Issue by behrangsa** [awslabs/kinesis-aggregation#29]
If we don't pass an explicit hash key to `addUserRecord` it will try to generate one from the partition key:

```java
    public boolean addUserRecord(String partitionKey, String explicitHashKey, byte[] data) {
        validatePartitionKey(partitionKey);
        partitionKey = partitionKey.trim();

        explicitHashKey = explicitHashKey != null ? explicitHashKey.trim() : createExplicitHashKey(partitionKey);
```

For some partition keys, the generated hash key could be invalid. For example if my partition key is:

```
String pk = new String(new byte[] {
                66,
                69,
                84,
                0,
                0,
                0,
                0,
                46,
                69,
                -17,
                -65,
                -67,
                -17,
                -65,
                -67
        });
```

Then `createExplicitHashKey(pk)` will generate: `-123`. To reproduce:

```java
public class Main {

    public static void main(String[] args) throws NoSuchAlgorithmException {
        String pk = new String(new byte[]{
                66,
                69,
                84,
                0,
                0,
                0,
                0,
                46,
                69,
                -17,
                -65,
                -67,
                -17,
                -65,
                -67
        });

        AggRecord record = new AggRecord();
        record.addUserRecord(pk, null, new byte[]{1, 2, 3});
    }

}
```

which throws:

```
java.lang.IllegalArgumentException: Invalid explicitHashKey, must be greater or equal to zero and less than or equal to (2^128 - 1), got -123
	at com.amazonaws.kinesis.agg.AggRecord.validateExplicitHashKey(AggRecord.java:464)
	at com.amazonaws.kinesis.agg.AggRecord.addUserRecord(AggRecord.java:329)
```

**Comment by behrangsa** [comment]
Just had a look at the KPL algorithm:

```c
auto digest = aws::utils::md5_binary(partition_key_);
for (int i = 0; i < 16; i++) {
  uint128_t p(digest[i]);
  p <<= (16 - i - 1) * 8;
  hash_key_ += p;
}
```

The Java version in Kinesis Aggregator, though, looks like this:

```java
for (int i = 0; i < this.md5.getDigestLength(); i++) {
	BigInteger p = new BigInteger(Byte.toString(pkDigest[i]));
	p.shiftLeft((16 - i - 1) * 8);
	hashKey = hashKey.add(p);
}
```

There are two issues with the Java version. First, `BigInteger` is immutable and as a result of that `p.shiftLeft((16 - i - 1) * 8);` is ignored. Second, in the KPL algorithm, each element of the `digest` array are converted to an unsigned integer first. If we fix these two bugs, we get:

```java
for (int i = 0; i < this.md5.getDigestLength(); i++) {	
    BigInteger p = new BigInteger(String.valueOf((int) pkDigest[i] & 0xFF)); // convert to unsigned integer
    BigInteger shifted = p.shiftLeft((16 - i - 1) * 8);
    hashKey = hashKey.add(shifted);
}
```

This at least generates valid hash keys however the generated values still don't match KPL's.

For example, for "abcd", KPL generates `E2FC714C4727EE9395F324CD2E7F331F` but this algorithm generates `8B08B37D3C9F2F244DB52A9A9861BD18`.
